import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "qjh",
  description: "Generated by create next app",
  icons: {
    icon: "./bg.jpg",
    shortcut: "./bg.jpg",
    apple: "./bg.jpg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning> 
    {/* suppressHydrationWarning */}
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div>根Layout</div>
        {children}
      </body>
    </html>
  );
}
